### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by niksajanjic** [mrbar42/ignore-emit-webpack-plugin#1]
```
(node:36648) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at IgnoreEmitPlugin.apply (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/ignore-emit-webpack-plugin/ignore-emit-webpack-plugin.js:40:14)
    at webpack (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack/lib/webpack.js:37:12)
    at options.map.options (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack/lib/webpack.js:28:55)
    at Array.map (<anonymous>)
    at webpack (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack/lib/webpack.js:28:40)
    at processOptions (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/yargs/yargs.js:552:18)
    at /Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/niksajanjic/Projects/MR2/pdf-service/templates/refactored_reports/node_modules/webpack/bin/webpack.js:157:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by niksajanjic** [comment]
PR: https://github.com/mrbar42/ignore-emit-webpack-plugin/pull/2
