### ISSUE TITLE
Cannot read property 'emit' of undefined with webpack 3.11.0

### ISSUE THREAD

**Issue by romanlex** [mrbar42/ignore-emit-webpack-plugin#5]
```
TypeError: Cannot read property 'emit' of undefined
    at IgnoreEmitPlugin.apply (/home/roman/Projects/fox.lo/client/node_modules/ignore-emit-webpack-plugin/ignore-emit-webpack-plugin.js:40:20)
    at Compiler.apply (/home/roman/Projects/fox.lo/client/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/roman/Projects/fox.lo/client/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/home/roman/Projects/fox.lo/client/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/home/roman/Projects/fox.lo/client/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/home/roman/Projects/fox.lo/client/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/home/roman/Projects/fox.lo/client/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

**Comment by mrbar42** [comment]
@romanlex thanks for this.
should be fixed in the latest version
